### PR TITLE
Switched to tls 1.1

### PR DESCRIPTION
**Pull request by alexandrubujor**

### CODE REVIEW

**Comment by dinesh** [comment]
@alexandrubujor Thanks for the PR, can you please make the test pass ?

I just had a brief look, It seems TLSv1.1/2 is only available in 2.7.9+ (for python 2.x) and 3.4+ (for python 3.x) and we should restrict this library to work only with those versions of python. I guess if you just remove the entry for `3.3` in `.travis.yml`, it will make the CI green. Let me know if you face any problem.

**Comment by ta** [comment]
@dinesh Could you add those changes in travis.yml to the PR. Support for TLSv1.0 will be turned of in a few days and I'd like to make a new release before then :)

**Comment by ta** [comment]
@alexandrubujor Thanks for the PR. We've incorporated your changes into https://github.com/QuickPay/quickpay-python-client/pull/14 and adjusted test parameters - as we are in a bit of a hurry with the TLS-stuff :)

**Comment by alexandrubujor** [comment]
No problem, I didn't have time to review this. 

Great news, please release the new modules ASAP so that all of users can upgrade their python client module.

**Comment by ta** [comment]
@alexandrubujor It is out - https://pypi.org/project/quickpay-api-client/ :) Thanks again for your contribution.

**Pull request closed without merging**
